### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by nbering** [Microsoft/cordova-plugin-code-push#107]
I'm having trouble diagnosing a download issue on android 5.0. I'm using `codePush.sync()` to get my update.

![image](https://cloud.githubusercontent.com/assets/4421371/14854448/c42531ca-0c5d-11e6-914d-894ceed48ea2.png)

I'm still trying to sort out exactly what's happening here, but it is finding a package in the deployment channel, but nothing ever appears in the network panel in DevTools, but it fails to download. Whitelist plugin hasn't been ruled out at this point, but this error is not very helpful I'd like to know where I should be going from here to diagnose the issue. I have two different apps built from the same base project and they are both behaving this way.

**Comment by lostintangent** [comment]
We've seen this issue once before and it was due to a whitelist issue. Could you double-check that your app includes the whitelist plugin? Also, could you double check that your access elements in the config.xml file enable all hosts (via the "*") or explicitly includes the two host names for CodePush (mentioned in our getting started docs).

 If both items check out, could you post the output of running "cordova plugin ls" and "cordova platform ls"? That way we can try to repro the exact ap conditions.

Also, are you using live reload (e.g. via the Ionic CLI)?

Thanks! We'll try to figure this out quickly for you.

**Comment by nbering** [comment]
Thanks for the reply. I was just writing a resolution when you posted.

### Malformed Whitelist Config
Turned out to be a whitelist issue. My config value looked like this:
```xml
<access origin="https://codepush.blob.core.windows.net/" />
```
The java code for whitelist was picking up on the trailing slash and only accepting that as a single path. Another value that should not be used with whitelist would be this:
```xml
<access origin="https://codepush.blob.core.windows.net/*" />
```
The asterisk solves the problem for android, but the generated parameters for the ios project are malformed by apple's standards, so they ignore the entry.

### The Correct Way
The only right way seems to be as follows:
```xml
<access origin="https://codepush.blob.core.windows.net" />
```

**Comment by lostintangent** [comment]
Ah right, yeah that is why we have the version without the trailing slash in our getting started docs. I'll look into making a better error message here, so that it's clearer what the issue is when it happens. Sorry for the confusion and thanks a lot for reaching out!

**Comment by nbering** [comment]
No problem. I'll close the issue now that it's sorted out. It's not really Code Push's fault, but documentation and helpful error messages make it easier for developers to sort out this kind of issue. Configuring the whitelist plugin has been one of the most needlessly complex processes I have ever encountered.
