### ISSUE TITLE
Update in first session but won't be forwarded to the "new" index.html

### ISSUE THREAD

**Issue by zwacky** [Microsoft/cordova-plugin-code-push#118]
Hey guys

I added a mechanic that will download the latest version and install it after the onboarding (note: first time users).
The update gets downloaded, installed and restarted. but it will not be pointed to the new index.html that lies somewhere in the code-push directory. therefore it's still the old version after the reload.
After I close the app and open it again, the latest version will now be served.

Is there a special way I could prevent this behaviour?

cheers!

**Comment by lostintangent** [comment]
@Simon Just so I fully understand, are you calling sync on app start (specifying InstallMode.ON_NEXT_RESTART), and then after the on boarding process is complete, you're calling restartApplication to force the install immediately at that time? Otherwise, if it isn't a new user, then the call to restartApplication wouldn't happen, and the update would be installed silently?

And the issue you're seeing is that after calling restartApplication, the app noticeably restarts, but displays the old version still?

**Comment by zwacky** [comment]
crap. I wasn't aware of `codePush.restartApplication()`... that solves it, thank you anyway 😅

**Comment by lostintangent** [comment]
Awesome! Glad I could help :)
