### ISSUE TITLE
execNotifyApplicationReady uses preference key instead of app supplied one

### ISSUE THREAD

**Issue by pke** [Microsoft/cordova-plugin-code-push#139]
I just discovered code in `execNotifyApplicationReady` that does

```
codePushReportingManager.reportStatus(new StatusReport(ReportingStatus.STORE_VERSION, null, appVersion, mainWebView.getPreferences().getString(DEPLOYMENT_KEY_PREFERENCE, null)), this.mainWebView)
```

on first app launch.
In our app we supply the keys to the `codePush.sync` call and do not have any keys in the preferences. The reason for that is that we have different deploy keys for development, staging and production for different (testflight) package versions.

What are the implications of that code above when there is no deployment key set in the preferences (which is not mandatory according to the docs).

**Comment by lostintangent** [comment]
Calling sync with a dynamically-provided deployment key is a first-class scenario, and the only ramifications of the code you pasted is that when a new user first installs your app from the store (or updates to a new binary), their existence won't be reported until after they install a CodePush update. So you're install metrics in the CLI might say that you have 300 total users, but you actually have 301. As soon as the 301st user installs a CodePush update, the CLI will report 301.

Since CodePush isn't trying to be a full-fledged user metrics/analytics solution, we haven't prioritized changing this behavior, since we're focused on just trying to show the distribution of users who have installed CodePush updates, which we do.

**Comment by lostintangent** [comment]
Are you experiencing any issues or were you just curious? :) I want to make sure we address any issues here, but as I mentioned, I don't believe there should be any.

**Comment by pke** [comment]
No, I was just wondering how it is supposed to work. Your explanation served me well. Sorry for miss-using the issue tracker. Is there any other way to ask such questions?

**Comment by lostintangent** [comment]
Asking questions via GitHub issues is totally cool. I didn't mean to imply that we didn't appreciate it, I just wanted to help myself and my team prioritize this bug for the day :) Many times, asking questions helps us see gaps in the docs, or tangential bugs, etc., so I always appreciate any and all feedback/questions.

**Comment by pke** [comment]
Cool. Just wanted to make sure. Other projects tend to prefer stackoverflow for general questions.
We just issued the first of many Cordova react code-push powered apps to the IOS store. Let's see how it goes.

**Comment by lostintangent** [comment]
@pke Awesome! Let us know how it goes :)
