### ISSUE TITLE
Unzip error

### ISSUE THREAD

**Issue by ashokkumar88** [Microsoft/cordova-plugin-code-push#149]
Hi,
I tried the plugin in my project and it is not updating the file. I checked in console and it is saying 

[CodePush]  Could not unzip package. -1", source: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (40)

Please help.

**Comment by lostintangent** [comment]
@ashokkumar88 Are you using the "release-cordova" command to release your update to the server? This error typically indicates that the update that was downloaded wasn't a zip as expected. This could happen if you use the "code-push release" command and specify a single file instead of your www directory as the contents of the update.

The "release-cordova" command will generate the appropriate update contents, and therefore, if you could confirm that you still hit this issue after releasing an update using it, we can investigate what may going on further.

**Comment by ashokkumar88** [comment]
@lostintangent Thanks for the quick response.

i am using the command "cordova-push release MyApp www/events.html "*"". If I will use the "release-cordova" command then every time it will zip all the files or it will automatically pick up the updated files only?

**Comment by lostintangent** [comment]
The client will only download the files which changed, so you can safely use the release-cordova command and let the server generate the appropriate diff updates for you.

**Comment by silhouettes** [comment]
@ashokkumar88, it looks like your problem will be solved by using `release-cordova` against your www directory. I'm closing this for now, but please let us know if you have any other questions or run into any toher issues!

**Comment by ashokkumar88** [comment]
Yes. The issue has been resolved. Thanks
