### ISSUE TITLE
Turn off first run in localpackage on resume

### ISSUE THREAD

**Issue by northkode** [Microsoft/cordova-plugin-code-push#150]
In our app we are checking for updates on app resume in cordova. 
In my code I have a function that checks if there is a localpackage update and if so check if it's first run and has a description and then show a modal with the change log. 

The issue however is when I put the app in the background and then come back first run is always true therfore the change log modal displays everytime the app is put in the background and then opened. 

I would think that first run should be set to false after a get package call  has already returned true the first time.

**Comment by silhouettes** [comment]
Hi @northkode, thanks for the feedback! I can discuss changing that property with the team, but would your specific issue be solved by using a JS boolean to check whether the change log has already been shown? Once it has been shown once, it will never need to be shown again, seeing as an update would reset the state of the app.

I'm somewhat hesitant to change the behavior here, because it seems more simple to me that `isFirstRun` will always be true until the app is restarted, rather than changing as a side effect of being called the first time. Also, if somebody calls `getCurrentPackage()` before a resume, `isFirstRun` will be `true`, and that property will persist after a resume regardless of what we do, so it makes sense to me to be consistent here. But I'm open to discuss this with you!

**Comment by northkode** [comment]
Makes sense. Ill code around it for now. Cheers!

**Comment by silhouettes** [comment]
Glad to be of service :) We're always looking to improve, so suggestions are always welcome!
