### ISSUE TITLE
code push error 

### ISSUE THREAD

**Issue by northkode** [Microsoft/cordova-plugin-code-push#155]
[CodePush] 0:
File /www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js at line 40, col 22 in logError

File /www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js at line 44, col 30 in invokeErrorCallback

File /www/plugins/cordova-plugin-code-push/bin/www/codePush.js at line 90, col 53 in callback

File /www/plugins/code-push/script/acquisition-sdk.js at line 42, col 25 in ?

File /www/plugins/cordova-plugin-code-push/bin/www/httpRequester.js at line 30, col 51 in onreadystatechange

happens from time to time.. can't nail down how... or why..

**Comment by silhouettes** [comment]
@northkode: I've tracked down the specific line of code that triggers the error (acquisition-sdk.js from the code-push repo), and it looks like it is triggered when the server responds with something other than a 200.

There can be a few possible reasons for this:
- 404: The deploymentKey in the request does not exist
- 400: The request was malformed
- 500: An internal server error or outage
- Potentially the request didn't make it to the server at all because of a network issue on the client

Would you be able to get a log the next time this happens? Alternatively, if you ping me at rihua@microsoft.com with your deploymentKey and the time it was triggered the next time this happens, I can look up the server logs directly.

**Comment by northkode** [comment]
Ok awesome. 
Is there anyway I can catch that nicely.. or at least make sure my user experience isn't wonky? 
I'll try a few tests to see if I can replicate on bad WiFi or no WiFi etc.  

Cheers

**Comment by silhouettes** [comment]
So I believe it will fail silently and shouldn't have any effect on your users, aside from them not receiving an update.

To be notified when an error happens, just add a [syncCallback when you call sync()](https://github.com/Microsoft/cordova-plugin-code-push#codepushsync), and check for a [syncStatus](https://github.com/Microsoft/cordova-plugin-code-push#syncstatus) of SyncStatus.ERROR ([example](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/samples/basic/www/js/index.js#L52)).

Hope that helped - let me know if that works for you, and if there's any other issues you run into!

**Comment by silhouettes** [comment]
Closing this as the issue seems to be explained, but feel free to re-open if there's anything else!
