### ISSUE TITLE
App gets updated even when newer (dev)bundle was deployed to device

### ISSUE THREAD

**Issue by pke** [Microsoft/cordova-plugin-code-push#157]
I deploy an app version with an updated `bundle.js` to the device using `cordova run`. When the app is run, code-push seems to think that an update is available since for the same target version there are indeed code-push deployments.

How can I prevent code-push from updating my dev version? Is the only way to increment the version in `config.xml`?

**Comment by silhouettes** [comment]
Yeah, I can see why that would be annoying. We'll try to figure out a way to address this next week, and it may or may not be similar to what we end up deciding to do for beta distribution scenarios (where the app store version often doesn't get bumped).

In the mean-time, probably the best thing to do is to run `code-push deployment clear` before deploying, do a matching CodePush release before deploying, or bump the version each time.

**Comment by sergey-akhalkov** [comment]
We've discussed the same issue here: https://github.com/Microsoft/react-native-code-push/issues/614 
And us result we believe that CodePush updates should not be tested while developing at all. Because it could lead to confusion and issues both for React Native and Cordova.
We think that the best workflow is: 
* debug - development; **code push is not being used here because it makes no sense**
* stage - stable version for testing. Changes are pushed here from the debug version
* production - what customers run. Changes propagated form staging.

@silhouettes, please let me know if the issue should be investigated or closed.

**Comment by sergey-akhalkov** [comment]
Closing this for now, please feel free to reopen if needed.
