### ISSUE TITLE
How to use for PhoneGap Build

### ISSUE THREAD

**Issue by ef33zy** [Microsoft/cordova-plugin-code-push#160]
Hi,

I have limited (to no) knowledge in using the Cordova CLI for my app, I use PGB.
According to the [documentation](https://github.com/Microsoft/cordova-plugin-code-push#phonegap-build), it says it supports PhoneGap Build, but there's limited info.

Including:
- adding the plugin (which I assumed to be `<plugin name="cordova-plugin-code-push"             source="npm" />`
- how to generate the platform-specific deployment keys as defined [here](https://github.com/Microsoft/cordova-plugin-code-push#getting-started) since the plugin install is slightly different on PGB from the CLI. (I intend to use the staging one I got from the cli for both platforms)

Also, can I use this for an app built using PGB, already installed on multiple test devices without uninstalling and re-installing them all?

Looking forward to your help and guidance.

Regards..

**Comment by geof90** [comment]
Thanks for the feedback. I agree our PhoneGap build documentation needs more work. It would be great if you could submit a pull request to improve our docs if you get it working!

> adding the plugin (which I assumed to be <plugin name="cordova-plugin-code-push" source="npm" />

That looks right.

> how to generate the platform-specific deployment keys as defined here since the plugin install is slightly different on PGB from the CLI. (I intend to use the staging one I got from the cli for both platforms)

You would create two CodePush apps using the `code-push app add MyApp-iOS` and `code-push app add MyApp-Android` commands, and then use the keys generated for each depending on whether you want Staging or Production.

> Also, can I use this for an app built using PGB, already installed on multiple test devices without uninstalling and re-installing them all?

You would have to re-install a build of your app that contains the CodePush plugin for all of them, so that the app is configured to check for updates from CodePush. Subsequently, for future updates you can start using the CodePush CLI to release updates.

**Comment by ef33zy** [comment]
@geof90 I'll try my best...

Couple of things though...
 - It seems like this is completely dependent on the CLI
 - However, considering PGB on the other hand is **completely independent** of the CLI I'm still struggling to use the plugin without having to install Cordova. This sorts of defeats the purpose of using PGB.
I've had to use the [general release](https://microsoft.github.io/code-push/docs/cli.html#releasing-updates-general), example error below when I use `release-cordova`:

`C:\Users\......>code-push release-cordova <myAppName> Android`
`[Error]  Unable to prepare project. Please ensure that either the Cordova or PhoneGap CLI is installed.`

Using the general release, I get the below error while the app is trying to update... 
Any help is appreciated.

![image](https://cloud.githubusercontent.com/assets/15075449/18295139/d3141772-7496-11e6-80ef-348654c335d4.png)

On a separate thought/note,per the plugin's [documentation](https://github.com/Microsoft/cordova-plugin-code-push#how-does-it-work), `CodePush plugin helps....by keeping your code....synchronized with updates you release to the CodePush server`, which it does by using `release-cordova` in the CLI.

For PGB then, I'm guessing the plugin will need to access the app's .ipa (iOS) & .apk (Android) files created by PGB? i.e. Shouldn't there be a way for the sync API to check against the PGB servers?  Or somehow getting the PGB files to the CodePush Servers?
 - This is so that we can still remain independent of the CLI , while `codePush.sync();` does what it does best... check for update to the .ipa & .apk on the PGB servers?

**Comment by bbohen** [comment]
I might be off here but it looks like while it is possible to use the code-push plugin with PGB it is mandatory that your project itself is capable of being used with cordova-cli. A project being built only with PGB doesn't need the CLI and to that extent doesn't have the platform directories that code-push is looking for.

The closest I got to an update with a non cordova-cli project was using `code-push release your-app ./path/to/www 1.1.0` which will take the contents of your www directory and upload them. From my brief test this updated the app (using `codePush.sync()`), but broke as expected. It did properly fall back to a working version.

> It's important that the path you specify refers to the platform-specific, prepared/bundled version of your app. 

I think the best current solution is to ensure your project can use cordova-cli as well as PGB which as @ef33zy notes kind of defeats the purpose of using PGB in the first place.

**Comment by sergey-akhalkov** [comment]
Closing this for now, please feel free to reopen if needed.

**Comment by byronigoe** [comment]
There are 2 extra steps, which are not yet documented, to use this plugin with PhoneGap Build.

First, you must include the zip plugin in addition to this one, as the zip plugin will not be added automatically. So, your config.xml should have:
```
  <plugin name="cordova-plugin-code-push" spec="1.11.18" />
  <plugin name="cordova-plugin-zip" spec="3.1.0" />
```

Second, you should download the APK and IPA files that PGB creates, open them with 7-zip (or similar archive software) and extract the extra files it creates. Namely:
```
cordova-js-src/
plugins/
cordova.js
cordova_plugins.js
```

Now you can use the normal "release" command instead of cordova-release, and all will work.
