### ISSUE TITLE
Too slow at first start up

### ISSUE THREAD

**Issue by keanuyaoo** [Microsoft/cordova-plugin-code-push#172]
It spend too much time at func:  UpdateHashUtils.getBinaryHash,
about 210s for 400 files; with : Android ,  HTC one m7;
Is there any way that build currentPackage.json  background  at first start up;

**Comment by mahesth** [comment]
Hi @ruslan-bikkinin, I have tried bundling the files / removing unnecessary files inside www folder. Now the folder contains 98 items including lib and app content. But still it is taking around 30 seconds - 1 minute for the update to trigger.

**Comment by ruslan-bikkinin** [comment]
@mahesth thank you for response.

> it is taking around 30 seconds - 1 minute for the update to trigger

Well, but it was taking around 7 minutes before, right? Nice speed up, i presume. Unfortunately, that's the only solution for now. If we will come up with enhancement, we will let you know about it.

**Comment by mahesth** [comment]
@ruslan-bikkinin  Yes... it was earlier 7 minutes. Waiting time reduced to 30 seconds itself is a huge difference.
I am just wondering if the hashing process is related to the network speed ?.

**Comment by ruslan-bikkinin** [comment]
@mahesth, no, the device main resource are consuming by hashing process is cpu (+ disk for listing files), because hashing performs on device for first update.

**Comment by mahesth** [comment]
Thank you @ruslan-bikkinin for clarification.

**Comment by raphjutras** [comment]
I have the same problem here...
The main goal of code-push is to ensure users always have the latest version, and the first build install is the most out-dated version. So this is crucial that the user should not have time to play with it, right?

I wanted code-push to update directly when starting the app (a new user download the outdated version on app-store). However, it takes approx 3-4mins until my app gets updated (until the "checking for update" is displayed in console), This is in contradiction with the main goal of code-push if my user have an outdated version for couple minutes and then need to restart the app while they are 'starting' using it? There are a lot of files in www, but this should be assumed, it is 'normal' when using plugins and a framework like Ionic. 

My codePush.sync(null, { installMode: InstallMode.IMMEDIATE }); is executed very fast when launching the app but it still take a long time before the update kicks in... Is there any possible way to speed-up that first update?? Like including a fake 'hash' or already calculated hash in the app-store build version? Or any way to force update without having to calculate hash and compare them (for downloadable build)?

Please help me because I think this plugin is extremely good, very well documented, I really appreciate it, but this problem is too important for me... Is there any fix?

Thank you very much

Raphaêl

**Comment by ruslan-bikkinin** [comment]
@raphjutras thanks for your response. We just discussed with team that providing option for disabling hash computing on the first check for update would be reasonable. But now we have a lot of more prioritized tasks to do, so we can't predict when we'll be able to pick it up. So in this case you can amend these [lines](https://github.com/Microsoft/cordova-plugin-code-push/blob/70b2ff80a51b1f40dd5e63c9b48be1522dcaa978/www/localPackage.ts#L487-L497) in your code or even contribute new PR introducing new option.

**Comment by raphjutras** [comment]
@ruslan-bikkinin Thank-you very much for the fast reply Ruslan and also for pointing me out where I should start with th ecode, I will take a look at this but I'm #00% new to TypeScript and everything related to Mobile world, I'll have a lot of reading to do until I can manage to generate my own modified plugin! I hope this idea will be included in next plugin versions, i'm convinced people would appreciate it! Thanks!
