### ISSUE TITLE
Weird prompt show when open app.

### ISSUE THREAD

**Issue by pvsong** [Microsoft/cordova-plugin-code-push#189]
Hi, 
Why this prompt show when I update version 
Thanks!
![screen shot 2016-11-24 at 2 42 59 am](https://cloud.githubusercontent.com/assets/9800579/20576308/0d1c121c-b1f0-11e6-9cf7-308dfc5e5b4a.png)

**Comment by pvsong** [comment]
Hello, 😃

**Comment by saurabhPV** [comment]
I am facing the same issue!!! Were you able to solve it? Also, I didn't observe this issue in android

**Comment by pvsong** [comment]
@saurabhPV, just create two key, android and IOS. and push release to specific one.

**Comment by sergey-akhalkov** [comment]
@pvsong, @saurabhPV - hi! 
@pvsong is right, we really have to create keys both for iOS and Android to avoid such kind of issues. From docs https://github.com/Microsoft/code-push/tree/master/cli#app-management we could see that 
>If your app targets both iOS and Android, we recommend creating separate apps with CodePush.

In case of Cordova it is very important to have different keys for multiple platforms, due to `code-push release-cordova myapp android` command runs `cordova prepare android`, so zip archive (generated for uploading to azure) contains code generated for Android only. So if an iOS app using CodePush tries to install update released by `code-push release-cordova myapp android` command it falls into the issue.

**Comment by sergey-akhalkov** [comment]
Closing this due to docs were improved https://github.com/Microsoft/code-push/commit/5f2f07e2e8060280a1eb93d255b4c6bd0ff7ee93, feel free to reopen if needed.
