### ISSUE TITLE
Android - New Binary Version Issues

### ISSUE THREAD

**Issue by TombolaShepless** [Microsoft/cordova-plugin-code-push#196]
When I create a new binary version, Code Push still uses the last package stored in the apps data and doesn't load the new binary versions assets. These are the steps taken:

1) Build and run v1.0.0 (fresh APK install on the device)
`cordova run android`

2) Create new code push for v1.0.0 (label v1)
`code-push release-cordova test android --deploymentName dev`

3) Download and install code push (label v1)

4) Create new code push for v1.0.1 (label v1, to test binary version restrictions)
`Manually bump config.xml to 1.0.1`
`code-push release-cordova test android --deploymentName dev`

5) Open app and ensure v1.0.1 (label v1) is NOT installed (this works as expected)

6) Create v1.0.1 APK and install on the device
`cordova run android`

7) Open app (should now be v1.0.1)

8) App is actually v1.0.1, but is loading assets from last successful code push (v1.0.0 label v1).

Is there something I'm doing wrong here? Or is this process dependent on the Play Store update process?

Any help is appreciated.

**Comment by Shepless** [comment]
Ok after a bit of digging it looks like [this](https://github.com/Microsoft/cordova-plugin-code-push/blob/adb82ddc2dfa1cf03128eb4db8137cce081c3798/src/android/CodePush.java#L273) is the problem. More specifically, [this](https://github.com/Microsoft/cordova-plugin-code-push/blob/adb82ddc2dfa1cf03128eb4db8137cce081c3798/src/android/Utilities.java#L65) is always returning a value that matches `deployedPackageTimeStamp`. See [this](https://github.com/Microsoft/cordova-plugin-code-push/blob/adb82ddc2dfa1cf03128eb4db8137cce081c3798/src/android/CodePush.java#L281) line. 

I'm not savvy with Android native development but [this](https://developer.android.com/reference/android/content/pm/PackageInfo.html#lastUpdateTime) looks like a more appropriate API for this task? It's been in the API since version 9 so support wouldn't be an issue. I guess theres a reason you guys are doing the way you are, I'm just not aware of it.

**Comment by TombolaShepless** [comment]
Apologies for flipping accounts here - have a personal and a work laptop (and accounts). I can confirm that the above is true. `getApkEntryBuildTime()` is returning "Tues Jan 01 1980" as is the `deployedPackageTimeStamp` so I think in both instances (the nativeBuildTime on the deployed package & the APK entry build time) are incorrect. I did a quick test using the above `PackageInfo.lastUpdateTime` approach for the APK and this returns the correct time. I'm not sure however where the `nativeBuildTime` is set? Is this part of the cloud service or CLI tooling?

Screen for your reference:
![screen shot 2016-12-07 at 18 43 44](https://cloud.githubusercontent.com/assets/11768442/20981816/fb6f9610-bcad-11e6-9ce5-11baf742bf21.png)

**Comment by chineseneo** [comment]
@TombolaShepless thanks man, I have run into the same issue as you, and your solution worked like a charm! I will modify the plugin and install it from local directory, so that the problem will be temporarily solved.

**Comment by TombolaShepless** [comment]
@chineseneo no worries mate. @silhouettes I have forked the repo and put the fix in, however I can't put a PR because I can't even compile the TypeScript - TSLint goes crazy, any ideas? I'd love to be able to put this up for PR to help you guys out.

**Comment by chineseneo** [comment]
@TombolaShepless as your solution suggests, you will only have to edit the java file. Why is type script bothering?

**Comment by TombolaShepless** [comment]
@chineseneo because when I don't know the plugin inside out, I don't know if that change has impacts elsewhere - thats why I want't to compile/transpile and run all UTs to be sure.

**Comment by chineseneo** [comment]
@TombolaShepless sorry buddy, I have no idea about that. Maybe when @silhouettes see this, he can help you.

**Comment by matrosov-nikita** [comment]
Hi @TombolaShepless, thanks for detailed description and investigation! 

> I'm not sure however where the nativeBuildTime is set? Is this part of the cloud service or CLI tooling?

The `nativeBuildTime` is stored in `/data/data/<PROJECT_ID>/files/codepush/currentPackage.json` and is being writen there after a successful update.

We've decided to use `classes.dex` as a source of APK build time, since there are some issues with other approaches:

a) `PackageInfo.lastUpdateTime` returns time when the package was installed, not built, and even this is sufficient to resolve this bug, this slightly changes the update behavior in case when prebuilt  APK is reinstalled on device.

b) adding a `buildConfigField` in gradle.properties with build timestamp so we can read it at runtime would require an additional configuration step

**Comment by TombolaShepless** [comment]
@matrosov-nikita thanks for getting back to me. Do you mean you are updating the code base to use `classes.dex` as the current implementation uses `resources.arsc`. Like I mentioned above, I really wanted to PR this for you guys to help out but the TypeScript compiling was going crazy :(

**Comment by HusseinMorsy** [comment]
@TombolaShepless for me the commit fa8e5a00e22ab90ad681a32ad8727d5e0e69e392 fixed the same problem you described in this PR

**Comment by Shepless** [comment]
@HusseinMorsy yes the PR has now been merged with the fix.

**Comment by sergey-akhalkov** [comment]
Closing this due to PR was merged, please feel free to reopen.

**Comment by davidofwatkins** [comment]
Hey all, I'm still having this problem after the fix was merged. Based on [this thread](https://code.google.com/p/android/issues/detail?id=220039) that @Shepless shared earlier, it looks like all files within the APK (including `classes.dex`) have their time stamps wiped in recent versions of the Gradle plugin:

> This is explicitly done to reduce changes between apks. If developers need this information in the apk, they can enable it by setting: "android.keepTimestampsInApk = true" in gradle.properties.

Fortunately, adding `android.keepTimestampsInApk = true` to my `gradle.properties` or `~/.gradle/gradle.properties` file as suggested fixes this for me, so this should be a simple fix.

**Some questions:**

* Is anyone else having this issue? Am I missing something?
* If the build process needs to be updated anyway, perhaps it would be clearer and more direct to just set and read from a `buildConfigField` in `gradle.properties` (see [here](http://stackoverflow.com/a/26372474/477632))?

To be clear, here's what I'm doing to test this issue:

1. Build and run v1.0 of my app.
1. Deploy a CodePush targeting this binary version (if not done already) and let my device receive the update.
1. Update my app version to v2.0 (that has no associated CodePush releases).
1. Assert that my mobile JS code is running out of the default native directory (`file:///android_asset/www/index.html`) and there is not an active CodePush package (`codePush.getCurrentPackage()`). This is what fails if I leave out `android.keepTimestampsInApk = true`.

**Comment by davidofwatkins** [comment]
In follow-up to my comment above, it seems that the same fix for `react-native-code-push` (https://github.com/Microsoft/react-native-code-push/pull/683) uses a `CODE_PUSH_APK_BUILD_TIME_KEY` constant instead of reading the date for contents of the APK.

@sergey-akhalkov, @matrosov-nikita: is there a reason the same fix wasn't applied here? It seems like a safer and more straightforward fix to me, especially considering #201 hasn't fixed the issue for me.

Thoughts? Would it be helpful if I opened a PR for this?

**Comment by silhouettes** [comment]
I'm in favor of using the same logic between the Cordova and React Native plugins, wherever possible, so that we can consolidate them together in the future. Do you guys have any thoughts?

**Comment by silhouettes** [comment]
When encountering issues going forward, it would also be good if we can verify that the behavior is the same across both OSes (iOS/Android) and both platforms (Cordova/React Native), so that we can use feedback in one area to fix issues in other areas before customers even report them.

**Comment by davidofwatkins** [comment]
@silhouettes I agree. I've opened a PR that uses the same fix as react-native-code-push, [here](https://github.com/Microsoft/cordova-plugin-code-push/pull/216).

**Comment by sergey-akhalkov** [comment]
Closing this due to #216 has been merged.
