### ISSUE TITLE
CodePush syncStatus:ERROR question

### ISSUE THREAD

**Issue by yoavpa** [Microsoft/cordova-plugin-code-push#197]
Hi,
We have a question regarding CodePush syncStatus:ERROR.
We see that in 0.8% of cases we get this error.

![screen shot 2016-12-08 at 6 10 13 pm](https://cloud.githubusercontent.com/assets/18379687/21017073/c19c039c-bd70-11e6-9469-fb7ec38cc9fd.png)

From your documentation i see that:
"An error occurred during the sync operation. This might be an error while communicating with the server, downloading or unziping the update. The console logs should contain more information about what happened. No update has been applied in this case."

I wanted to ask how i can get the console logs for that case

Thanks,
Yoav

**Comment by vladimir-kotikov** [comment]
Hi @yoavpa

You could try to diagnose these problems using a telemetry/crash reporting service to see if there are any crashes, that might correllate with updates. You can also try to enable console logs in release build on your device by following [this instruction](https://github.com/Microsoft/react-native-code-push#debugging--troubleshooting)  but note that these logs are seen on your local machine only (unless tou're not sending them to telemetry)

**Comment by slorber** [comment]
Hi,

@vladimir-kotikov I am using crash reporting GetSentry/RavenJS but I'm unable to get more infos because it logs only the string part of the logs.

![image](https://cloud.githubusercontent.com/assets/749374/22223007/82209c2e-e1b9-11e6-8fe8-61e7b03dcd66.png)

Isn't it possible that the sync callback could be called with an additional payload so that we can get some additional useful data related to this sync status? For example it would be usefull to allow us to handle ourselves the JS error that was thown, in this case I would be able to log it properly in my crash reporting system myself.

**Comment by pniko** [comment]
As part of our migration into Mobile Centers new backend we will have enhanced crash capabilities which don't exist for CodePush today. We will be working on a new feature for crashes later on this year that should support what you are looking for here. I would look out for that announcement from our team in the near future!
