### ISSUE TITLE
Reverting clients to start from default www/ folder

### ISSUE THREAD

**Issue by scopsy** [Microsoft/cordova-plugin-code-push#210]
code push plugin alters the location of the index.html file, So when user downloads app from the store they are "stuck" in the old directory untill they download the new version from the store. Is it possible to force users to revert to the default www/ folder location ? (I'm speaking about future uses when I need to rely only on store updates)

**Comment by max-mironov** [comment]
Hello @scopsy, sorry for slow response. So do I get it right that your issue is that users are still using old version packages even if they have installed new version of the app from store? 
If yes than this issue should be fixed with the latest https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/v1.9.3-beta  release. Please let us know if this fixes your issue.

**Comment by max-mironov** [comment]
@scopsy, just a friendly ping :)

**Comment by scopsy** [comment]
@max-mironov Hey Max, sorry for not answering. Was on a vacation, Yes it seems like a related issue. I will check this release.  Thanks a lot!
