### ISSUE TITLE
Details on how copying the asset files work

### ISSUE THREAD

**Issue by dested** [Microsoft/cordova-plugin-code-push#239]
I am using a native branch of cordova named Tabris.JS (https://github.com/eclipsesource/tabris-js). This framework allows native views rendered via javascript, much like React Native or NativeScript. Unlike React Native or NS, it uses a full cordova project (and plugin) ecosystem. I am trying to get code-push working in it, and I can make it all the way to the install. The install happens just fine but upon restart there are no changes. I am hoping for more insight into how/when/where the new files clobber the assets/www folder so I can track down where the disconnect in tabris occurs. I am currently only testing on android using Cordova 6.5.0.

Any insight is greatly appreciated! Anything I find I can share to allow code-push to natively support Tabris.JS. 

Thanks!

**Comment by sergey-akhalkov** [comment]
Hi @dested, thank you for reaching us. 
Here is basic workflow, please let me know if you have any questions or need more details:
1. First of all, we need to prepare update contents we want to release via CodePush. To achieve it, we need to perform `code-push release-cordova` command or perform vanilla `code-push release` command. To prepare CodePush update contents CodePush CLI performs `cordova prepare` command. Generated client side files are present in `.\platforms\android\assets\www` folder. CodePush CLI uses this folder further to upload update contents to the CodePush Server.
2. Then CodePush SDK [checks for updates](https://github.com/Microsoft/cordova-plugin-code-push/blob/adb82ddc2dfa1cf03128eb4db8137cce081c3798/www/codePush.ts#L403), and in case of any available updates CodePush SDK performs [package download](https://github.com/Microsoft/cordova-plugin-code-push/blob/adb82ddc2dfa1cf03128eb4db8137cce081c3798/www/codePush.ts#L351). Package installation starts [here](https://github.com/Microsoft/cordova-plugin-code-push/blob/adb82ddc2dfa1cf03128eb4db8137cce081c3798/www/codePush.ts#L346) just after download.
3. New path, that maps to the update contents folder, generates [here](https://github.com/Microsoft/cordova-plugin-code-push/blob/adb82ddc2dfa1cf03128eb4db8137cce081c3798/www/localPackage.ts#L67). Then we [unzip downloaded package](https://github.com/Microsoft/cordova-plugin-code-push/blob/adb82ddc2dfa1cf03128eb4db8137cce081c3798/www/localPackage.ts#L88). Then we [start moving assets to the new location](https://github.com/Microsoft/cordova-plugin-code-push/blob/adb82ddc2dfa1cf03128eb4db8137cce081c3798/www/localPackage.ts#L274).
4. Then we need to [check if we can find start page](https://github.com/Microsoft/cordova-plugin-code-push/blob/adb82ddc2dfa1cf03128eb4db8137cce081c3798/src/android/CodePush.java#L311). If so, [installation process ends successfully](https://github.com/Microsoft/cordova-plugin-code-push/blob/adb82ddc2dfa1cf03128eb4db8137cce081c3798/src/android/CodePush.java#L200).
5. Then we need to restart the app to [navigate to local deployment if exists](https://github.com/Microsoft/cordova-plugin-code-push/blob/3fe22769745a5112b163dc857fab58e9037cef9c/src/android/CodePush.java#L484)
6. Due to using another start page location, we have to use relative paths (that maps to the images, js files, html files and etc.) instead of absolute to make it possible to apply updated files downloaded via CodePush.

**Comment by dested** [comment]
Ahh, I see. So you never actually physically overwrite the www folder that was initially shipped with the APK or IPA, is that right? You simply tell it to point to a new Start Page. If this is the case, then unfortunately Tabris will never work, as it internally depends on very specifically loading up the files from that initial www folder. Was there a reason you opted to go this route vs simply crushing the www folder with new contents?

**Comment by sergey-akhalkov** [comment]
@dested, 
>So you never actually physically overwrite the www folder that was initially shipped with the APK or IPA, is that right? You simply tell it to point to a new Start Page.

Correct, we cannot modify any files in apk's assets folder, due to it is read-only in runtime, so we have to save CodePush update into internal storage to use it further.

>Tabris will never work, as it internally depends on very specifically loading up the files from that initial www folder. 

I'm not sure if it's clear for me, could you please clarify it? As for now `newPackageLocation` - is a full copy of `.\platforms\android\assets\www` folder, except files that has been modified with CodePush update. So initial www folder and www folder created by CodePush are the same, except updated files.

Please let me know if you have any questions.

**Comment by sergey-akhalkov** [comment]
Hi @dested, I'm closing this for now, please feel free to reopen in case of any questions or issues.
