### ISSUE TITLE
After first update , it's always alert (CodePush, The application is up to date.)

### ISSUE THREAD

**Issue by system65** [Microsoft/cordova-plugin-code-push#253]
### Description

i'm using the manual update as below :

`
$ionicPlatform.ready(function() {
      window.codePush.notifyApplicationReady();
     
var onError = function (error) {
          console.log("An error occurred. " + error);
      };

      var onPackageDownloaded = function (localPackage) {
          console.log("Package downloaded at: " + localPackage.localPath);
          localPackage.install(onInstallSuccess, onError, { installMode: InstallMode.ON_NEXT_RESUME, minimumBackgroundDuration: 120, mandatoryInstallMode: InstallMode.ON_NEXT_RESTART });
      };

      var onProgress = function (downloadProgress) {
          console.log(downloadProgress.receivedBytes + " of " + downloadProgress.totalBytes);
      };

      var onUpdateCheck = function (remotePackage) {
          if (!remotePackage) {
              console.log("The application is up to date till today.");
          } else {
              console.log("update Package hash: " + remotePackage.packageHash);
              remotePackage.download(onPackageDownloaded, onError, onProgress);
          }
      };

      window.codePush.checkForUpdate(onUpdateCheck, onError);
});
`

After the first update, it's always alert (CodePush, The application is up to date.)
[Log] [CodePush] Checking for update.
[Log] [CodePush] App is up to date.

**Comment by sergey-akhalkov** [comment]
Hi @system65, thanks for reaching us. Do I get it right if you have released first CodePush update and successfully installed it, then you have released second CodePush update, but the app is not able to receive and install it? If not, could you please be more specific regarding what the issue is and what you are expecting for?  
It also would be helpful if you could provide us with the following info:
* deployment history `code-push deployment history <appName> <deploymentName>`
* cordova-plugin-code-push version: 
* List of installed plugins:
* Cordova version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

**Comment by sergey-akhalkov** [comment]
@system65, just a friendly ping.

**Comment by system65** [comment]
problem solved when using` <deploymentName> Production`
