### ISSUE TITLE
App can get stuck in a bricked state

### ISSUE THREAD

**Issue by aaronorosen** [Microsoft/cordova-plugin-code-push#254]
I just ran into an odd issue I've never encountered with codepush. 

I pushed out a mandatory update to my staging group and it seemed to brick the app running on my phone and wasn't able to revert back. I deleted the app from my phone and had it download the same update via codepush and it worked.  

    <plugin name="cordova-plugin-code-push" spec="~1.9.3-beta" />

**Comment by sergey-akhalkov** [comment]
Hi @aaronorosen, thanks for reaching us, as I've mentioned in the email I've sent you - we are investigating an issue when user closes the app while it is installing an update - it probably may cause the same symptoms as you’ve described above. We'll let you know if any updates.

**Comment by aaronorosen** [comment]
I just encountered this issue again with my app on my device. I didn't close the app either while it was updating thou.

**Comment by sergey-akhalkov** [comment]
Hi @aaronorosen, got it, due to it is another issue - could you please provide us source code or minimal version of the app where the issue reproduces? I've also tried to reproduce it using our [sample app](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic) but with no luck, so we need to figure out repro steps or conditions when the issue reproduces.

Could you please also share us with the following info:
* cordova-plugin-code-push version: 
* List of installed plugins:
* Cordova version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

**Comment by sergey-akhalkov** [comment]
@aaronorosen, just a friendly ping.

**Comment by sergey-akhalkov** [comment]
Closing this for now, please feel free to reopen if any updates.
