### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by pke** [Microsoft/cordova-plugin-code-push#27]
I'm surprised you are not offering support for your own operating system.
Shouldn't be hard to use WinRT as the technology stack?
Why isn't the plugin not depending on a common Cordova file transfer plugin?

**Comment by dlebu** [comment]
We are definitely looking into supporting Windows. CodePush is enabled by downloading new content from the server in the device's local storage. We then unpack and load that content in the main Cordova webview, while still being able to access all the plugin functionality. For Android and iOS, when loading local content in the Cordova webview, all the plugin APIs are still available. For Windows, due to the nature of the Cordova implementation for the platform, we don't get that for free since WinRT APIs are not available to local protocols ms-appdata and ms-localstream. We are looking into ways we could implement Windows support without breaking the experience for any Cordova plugin, whether it's a core or a custom plugin.

**Comment by dlebu** [comment]
Regarding your file transfer plugin question, [we do take a dependency](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/plugin.xml#L10) on the core cordova-plugin-file-transfer.

**Comment by lostintangent** [comment]
I'm going to close this issue for now, since it isn't going to be immediately actionable for us. We're working with the Windows team to unblock the issue that @dlebu mentioned above, and hope to resolve this very soon. We'll keep everyone posted on the progress here!

**Comment by pke** [comment]
ok. I implemented code-reload from ms-appdata:///local in a non-cordova app myself in the past. It was easy. I'll have a look in how the cordova windows plugin handles the loading of scripts. I'd have thought they just dump them to ms-appdata:// and load them from there.

**Comment by geof90** [comment]
@pke code-reload from ms-appdata:///local is okay, the we do that for the [CodePush - React Native for Windows plugin](https://github.com/Microsoft/react-native-code-push/blob/master/windows/CodePushConstants.cs#L17). The problem seems unique to Cordova apps on windows which run on the Windows Web Apps (WWA) platform. The platform blocks access to WinRT APIs if you are on local protocols ms-appdata and ms-localstream as @dlebu mentioned.

**Comment by slorber** [comment]
Hey,

Any progress on this issue?

I'm just publishing my UWP Cordova app to the store and it feels to me a big step backward as I now have to submit to windows store and wait for approval before deploying a new non-compatible API backend.

I'm not a Windows platform expert at all, and I think i'm using "remote protocol". Isn't there a way to at least make it work for remote protocols?

**Comment by pke** [comment]
As I wrote I had to working in 2013 in Windows 8 already (using my own solution not codepush). But MS might have tightened the security of remote code reload.

**Comment by jokeyrhyme** [comment]
It might be worth switching from Cordova to Electron for Windows 10. This doesn't work on Windows Phone / Windows Mobile, but it is probably a better solution for desktops / laptops.

**Comment by slorber** [comment]
@pke what's your solution? can it work in Windows10 / UWP?

**Comment by nelsonec87** [comment]
Hi, any progress/timeline?
