### ISSUE TITLE
Delay after update

### ISSUE THREAD

**Issue by napcat** [Microsoft/cordova-plugin-code-push#291]
### Description
I'm testing CodePush and it works great, but here's an issue. After an update the app starts slow, it takes more time to boot. 

For exemple, install the app... takes 1/2 secs to boot and be in the main screen.
Release an update and install it and restart the app.
The app now (with the new update) takes about 5/6 seconds to boot.
Go to Android settings and clean the cache.
The update is removed and the app boots again with a 1/2 seconds delay.

Is this suposed to happen?
Is it normal?

### Additional Information
* cordova-plugin-code-push version: 2.1.0-beta
* Cordova version: 6.5.0
* iOS/Android/Windows version: 4.4.2
* Does this reproduce on a debug build or release build? Debug, didn't test on a release build yet.
* Does this reproduce on a simulator, or only on a physical device? Physical device

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment]
Hi there @napcat and thanks for reaching us. 
Is it possible that your issue is the duplicate for https://github.com/Microsoft/cordova-plugin-code-push/issues/221?
If so - do you mind if we have single point of discussion in one place (e.g. move to #221 as it was created earlier) so it would be easier for us to collaborate?

**Comment by napcat** [comment]
Ok... I wrote my problem in the other issue.
Thank you for point me that issue.

**Comment by max-mironov** [comment]
Thanks!
