### ISSUE TITLE
[Feature] Download now and install later

### ISSUE THREAD

**Issue by AgDude** [Microsoft/cordova-plugin-code-push#305]
### Description
I would like to manually manage the update process. but download an update as soon as it is available. So the workflow I would like is:

* Check for updates
* If update is available download it immediately
* Give the user the option to install (which they may decline) I do not want to force the update even on an app restart.

Currently I can download the package, but if I don't call `install` immediately after downloading I have no way to access the `localPackage` later. `getPendingPackage` only returns the package if it has already been installed. 

checkForUpdate or download to find the package which is already downloaded so I can access it and install it at any time.

**Comment by ruslan-bikkinin** [comment]
Hi @AgDude  and thanks for reaching us.

> but if I don't call install immediately after downloading I have no way to access the localPackage later

Yes, you have, you can pass `localPackage` as parameter to dialog window implementation and continue to work with it later. You can take a look on [these](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/samples/advanced/www/js/index.js#L110) lines of our sample demo project for example.

Please let us know if you have any questions or any updates.

**Comment by AgDude** [comment]
From what I see in that example, the reference to localPackage is being retained in memory between the download and install functions. I would like to allow a long period of time, and potentially app restarts between the time the package is downloaded and installed.

**Comment by AgDude** [comment]
I have just tun into another related scenario. My app periodically checks for updates, and downloads if available. The user then has the option to install at some later time. Since there is no way to determine if we have an update downloaded and ready to install, we may start another download, deleting the one we have locally. If then while the new copy is being downloaded the user tries to install the update it fails.

It fails with the error `could not unzip package`

In order to be able to fully customize the user update experience, we need a function to identify the status of any package which has been downloaded but not yet installed.

**Comment by ruslan-bikkinin** [comment]
@AgDude we understand your use case and it looks very specific. Most of the CodePush users are using the existing ways to install updates and they want to install update immediately after its download (and apply it at least on the next app start). Currently we are extremely backlogged, but we will be watching for similar feature requests from users to consider opportunity to implement it in the future. Currently we suggest you to use following workflow:

1. Set installMode to ON_NEXT_RESTART
2. Call `codePush.checkforUpdate`  
* if user declines to download and install update then wait until next `codePush.checkForUpdate` call to ass again
* If user accept to download and install update, but don't want to restart app then download and install update
4. When user performs manual restart of app from UI - execute `codePush.restartApplication` in order to update will be applied on next app start.
5. When user kills app using task manager - update will be applied on next app start automatically.

> If then while the new copy is being downloaded the user tries to install the update it fails. It fails with the error could not unzip package

Please submit new issue for this, we will investigate it.

**Comment by sergey-akhalkov** [comment]
Closing this for now, we'll reopen in case of similar/same feature requests, please also feel free to reopen.
