### ISSUE TITLE
Error Status 503, Service unavailable on checking for update

### ISSUE THREAD

**Issue by Wallethub** [Microsoft/cordova-plugin-code-push#314]
Hi,
This issue #272, #281, #287, #300 and #304 and also mentioned #1028 has started coming up again. Same scenario and has started since 3:26:05 PM EDT today and has been coming since then.
Please check if there is an issue on your side.

Thanks,
Wallethub Team

**Comment by ruslan-bikkinin** [comment]
Hi @Wallethub and thanks for letting us know, we’ll check this ASAP. Thanks for your patience.

**Comment by bdb80** [comment]
We are facing the same issue on one Android device.
when navigating to the /updateCheck uri in browser the result is fine, but for some reason the device receives a 503.

Please note that on 2 of our devices we dont have this issue.

**Comment by Wallethub** [comment]
Hi @ruslan-bikkinin thanks for looking into it, any news so far?

**Comment by max-mironov** [comment]
Hello @Wallethub!
We apologize for not getting back info for you faster. 
It turns out that we were receiving a higher than normal load around that period and had just reset the services right around the time you saw them stop. You'll be happy to know we are in the process of moving over to a new architecture over the nearest time that will help us better manage the resources powering the CodePush backend. As part of this, we will be exiting beta and providing a proper SLA so everybody know what to expect from us going forward. 
Thanks again and sorry for inconvinience.

**Comment by max-mironov** [comment]
Closing this for now as the issue has being mitigated, please don't hesitate to update us  immediately if you have any questions or see this issue again.
