### ISSUE TITLE
Plugin doesn't support this project's cordova-android version

### ISSUE THREAD

**Issue by zhangzhaojun** [Microsoft/cordova-plugin-code-push#319]
When I installed cordova-plugin-code-push@latest , I got the following prompt:
```
Installing "cordova-plugin-file" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.1.2, failed version requirement: >=6.3.0
```
Who can tell me the solution?

**Comment by max-mironov** [comment]
Hello @zhangzhaojun, unfortunately I believe that the only solution here would be to upgrade to Cordova 6.3.0 or later (because of this one: https://github.com/apache/cordova-plugin-file/blob/master/plugin.xml#L33). 
`cordova-plugin-file` is our 3rd party dependency and we should be in sync with their requirements.
