### ISSUE TITLE
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0

### ISSUE THREAD

**Issue by JohnD0580** [Microsoft/cordova-plugin-code-push#385]
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement: <6.3.0 Skipping 'cordova-plugin-compat'

I can't get it working with cordova-android 7, i downgraded my android platform to 6.2 but then it won't build in Android Studio 3

Can you guy fix this so it works with cordova-android 7 ?

**Comment by alexandergoncharov** [comment]
Hi @JohnD0580 ,

Thanks for reporting.
This happens because 'cordova-plugin-compat' is deprecated. All functional of 'cordova-plugin-compat' already included in cordova-android 6.3 and higher and 'cordova-plugin-compat' should NOT be installed.
If your cordova-android version less than 6.3 then 'cordova-plugin-compat' will be installed.
Please find more info on 'cordova-plugin-compat' repo: https://github.com/apache/cordova-plugin-compat
If you really need to use 'cordova-plugin-compat' with cordova-android 7 then you can write to repo which I provide above because we don't work on 'cordova-plugin-compat'.

If you have questions or concerns please feel free to reopen issue.


Thanks,
Alexander
