### ISSUE TITLE
Plugins versions are hardcoded afterPluginAdd.js

### ISSUE THREAD

**Issue by visiongeist** [Microsoft/cordova-plugin-code-push#434]
### Description

Due to the fact that plugins are hardcoded in:
https://github.com/Microsoft/cordova-plugin-code-push/blob/98faa5de00895347a12cb6366839c2c5478da3c2/hooks/afterPluginAdd.js#L18-L35
during installation if you have newer versions of the dependency in your package.json, these may be ignored if the cordova plugin system decides to install cordova-plugin-code-push first. 

### Reproduction

* cordova plugin add cordova-plugin-file-transfer
* cordova plugin add cordova-plugin-code-push
* cordova platform add ios

**Comment by alexandergoncharov** [comment]
Hi @visiongeist ,
Thanks for reporting!

Yeah, we have to keep it so, because this is last version of cordova-plugin-file which support old cordova-android version less then 6.3.0. We wouldl ike to support new and old android version. We put this logic for installing this plugins with specific version in hooks because we would like to keep possibility to change plugin version for users if they would like to do so.

Please let me know if it was helpful or you have any questions.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @visiongeist 

I'm going to close this issue as I haven't heard from you in a while unfortunately.
Please feel free to reopen this issue if you have any questions.

Thanks,
Alexander
