### ISSUE TITLE
Need improve the user experience

### ISSUE THREAD

**Issue by ryanlin1986** [Microsoft/cordova-plugin-code-push#45]
1, User need to know what's updated
2, Provide the API to show user the package download progress dialog(user should be able to cancel download it if not a mandatory update)

**Comment by lostintangent** [comment]
For #1, there's actually an option you can specify to sync called "appendReleaseDescription" that will add the value of the description property you specified when calling the "release" command from the CLI. Let me know if that is what you had in mind.

If you're referring to showing a "What's New?" dialog after an update is applied, as opposed to explaining what an update contains before installing it, you could use the "codePush.getCurrentPackage()" method to retrieve the metadata about the running update, which will include the description as well as a property called "isFirstRun" which indicates whether this is the first time the app has run since installing the update. The later is valuable since you obviously wouldn't want to show the dialogue on any app run but the first after the update.

Do either of those options work for you? Could we make it simpler or improved in any way? Any feedback here would be great!

Regarding the second comment, we're actually about to release support for download progress very soon. The APi won't automatically display a dialog, but it will provide the hooks for the app to listen for progress events and update its own dialog.

**Comment by ryanlin1986** [comment]
Thanks for the reply, for #1, great to hear the option appendReleaseDescription is already there.
And even greater is what's upcoming regarding the #2, even better than what I thought.

**Comment by lostintangent** [comment]
That's great to hear, thanks for following up. Stay tuned for the second update, it should be sometime in the next couple days.

**Comment by dlebu** [comment]
@ryanlin1986 We released [1.3.0-beta](https://github.com/Microsoft/cordova-plugin-code-push/releases) on Friday. This brings the download progress callback API and other features. If you are using `sync`, make sure you account for the fact that starting with this update, it is being called more than once, because we introduced intermediate statuses. Please keep the feedback coming.
