### ISSUE TITLE
Can this plugin release a part of the source in www 

### ISSUE THREAD

**Issue by duchuy294** [Microsoft/cordova-plugin-code-push#467]
When i use this command: 
**code-push release hello .\platforms\android\app\src\main\assets\www 1.0.0**
It update all of the file to my device app, but i just want to update a part of file, for example:
**code-push release hello .\platforms\android\app\src\main\assets\www\js\module\sendemail 1.0.0**
Is it possible? Thank you so much.

**Comment by alexandergoncharov** [comment]
Hi @duchuy294,
Thanks for reporting!

Unfortunately you can't release some part of file. But you can release single file instead of folder.

Please let me know if it was helpful or you have any questions.

**Comment by duchuy294** [comment]
Hello @alexandergoncharov 
Thank you for your reply!

The first I only update the file macro.js and i just want to release this file follow these command
cordova prepare
code-push release hello .\platforms\android\app\src\main\assets\www\js\module\macro\macro.js 1.0.0

Then I install update from app and it throw the error follow these below image:

![issue1](https://user-images.githubusercontent.com/16128177/48256406-081ea280-e442-11e8-829c-0617a4dd8f2e.PNG)
![issue2](https://user-images.githubusercontent.com/16128177/48256399-fdfca400-e441-11e8-91de-d1d47a1129c8.PNG)
![issue3](https://user-images.githubusercontent.com/16128177/48256401-005efe00-e442-11e8-92bd-795a192aac83.PNG)

**Comment by alexandergoncharov** [comment]
It is strange issue. It looks like some hash calculation is broken.
Could you please share some dummy project with reproducing issue? I would like to debug it

**Comment by duchuy294** [comment]
Hello @alexandergoncharov 

This file below is my hello world Cordova source project for you debuging.

[www.zip](https://github.com/Microsoft/cordova-plugin-code-push/files/2570317/www.zip)

**Comment by duchuy294** [comment]
I just want to know how can i release the file **(not folder)** which will be updated on the application.
Waiting for your response. Thank you very much.

**Comment by alexandergoncharov** [comment]
Hi @duchuy294 ,

Looks like I found the reason of your issue. Unfortunately you have to make full CodePush release for first time. It is necessary because it isn't possible to mix binary files and CodePush file. CodePush can replace some files only on installed release. So, after installed first full release you can release single file and CodePush replace it.

For release full release please use `release-cordova` command.
After installing this full release - single file release should works.

Please let me know if it was helpful or you still have this issue.

**Comment by duchuy294** [comment]
Hi @alexandergoncharov ,

After perform full release, then how can I release a particular file.

For example, after release then I update 2 file:
                    www/index.html ==> Change Header content
                    www/js/module/macro/macro.js ==> Change version

And I want to release only the file www/js/module/macro/macro.js, although the file index.html was changed but I am not want to release this file.

So after that the application only install the change of macro **not** index

In general, which command to help me perform above issue.

Thank you for your enthusiastic support.

**Comment by alexandergoncharov** [comment]
Hi @duchuy294 ,

Yeah, I reproduced your issue. It is strange. I'll investigate it a bit later and let you know.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @duchuy294,

I investigated your case and found that it isn't possible to release single file because CodePush has logic for comparing releases and generating diff for device downloading.
For example if you have 1, 2 and 3 files, made changes only in 1, made release and then CodePush  found that changes was only in 1 file and prepare zip only with this files(and metadata) for device downloading to prevent unnecessary downloading size as files can be really big. But please notice that this comparing works only for CodePush releases(not binary). First update will be installed fully.
   
For this logic CodePush should take full www folder for checking if something was deleted. And in this case if we release single file CodePush think that all files was deleted except this one which you changed.

So, my recommendation is just make changes in file which you would you like to release and release update with `release-cordova` command for automatically preparing. After that you can continue developing. One more approach if you have to change 2 files(like in you example) you can revert changes manually which you don't want to release and release full www folder with `release` command.

Please let me know if it was helpful you have any questions.

Thanks,
Alexander

**Comment by duchuy294** [comment]
Hi @alexandergoncharov ,

Your suggestion are really make sense and helpful. 

Thank you for your supporting.

**Comment by alexandergoncharov** [comment]
I was glad to help :)

Feel free to ask any question in the future.
