### ISSUE TITLE
add download size info to remotePackage

### ISSUE THREAD

**Issue by zwacky** [Microsoft/cordova-plugin-code-push#51]
there are *description* and *packageSize* that are undefined. i think it'd be great if you can tell the user before hand what he can expect size-wise.

```
// current remotePackage dump
appVersion: "0.4.32"
deploymentKey: "8960f81c-xxx"
description: undefined
downloadUrl: "https://codepush.blob.core.windows.net/storagev2/xxx"
failedInstall: false
isMandatory: false
label: "v3"
packageHash: "fbc201670xxx"
packageSize: undefined
```

**Comment by lostintangent** [comment]
The packageSize property should definitely be populated within a remote package response. Let us take a look into this as it may be a bug. Thanks for reporting it!

**Comment by dtivel** [comment]
Thank you for reporting this.  I checked in a fix for the CodePush service not reporting package size and updated the live service.  The `packageSize` property should be correct now.  Please let me know if you see otherwise.

As for the `description` property, did you specify an optional description (with the `--description` parameter) when you released an update?  The description should be empty by default.

**Comment by zwacky** [comment]
cool, I'll try it out tomorrow.

yeah I just omitted the description, that works.

**Comment by lostintangent** [comment]
I'm going to close out this bug as resolved, but please re-open it if you experience any issues when testing the new `packageSize` property tomorrow. Thanks again @zwacky!

**Comment by zwacky** [comment]
just wanted to confirm: the `packageSize` is correctly showing now. 

also, dunno what i was doing wrong before, but the actual update itself is downloading only parts of it, so the diffing is working perfectly.

**Comment by dtivel** [comment]
Fantastic!  Thank you for confirming, @zwacky.  Please let us know if you run into any other issues.
