### ISSUE TITLE
switching deployment keys possible?

### ISSUE THREAD

**Issue by zwacky** [Microsoft/cordova-plugin-code-push#52]
is switching deployment keys possible or would it mess with the diffing and such?

given there would be ios-production and ios-development.

**Comment by dtivel** [comment]
When you release an update, the service generates a diff package from the previous release to the latest release.  This diff package is handed out to clients upgrading from the previous to latest release.  When a client running an earlier release or a release from a different deployment checks for an update, they will receive the full update, not a diff.

**Comment by lostintangent** [comment]
The sync and checkForUpdate methods allow specifying a deployment key specifically to support dynamically changing deployment keys are runtime. As @dtivel mentioned, the diffing support may not work, but the user experience would be equivalent otherwise. We have quite a few users doing this to support allowing end users to switch to the staging deployment for "early access" and other scenarios.

**Comment by zwacky** [comment]
that sounds perfect for our use case, too. thanks for clarifying.
