### ISSUE TITLE
Does the plugin store updates?

### ISSUE THREAD

**Issue by DefaultAlias** [Microsoft/cordova-plugin-code-push#93]
Hi, i've implemented codepush into our app and everything seems to be working well with the exception of killing the app and restarting. Is there anything specific i need to do to ensure that the app starts from the most recently downloaded update as opposed to the app store version? what's happening now is it will load the app store version and fetch the download for the update. 

Info that might be important, we're using the lastest codepush version and cordova 5.4.0.

My code for handling the update is pretty standard: 
```
btnHandler = function(){
    window.codePush.sync(
        function (syncStatus) {},
        {
            updateDialog: true, 
            installMode: InstallMode.IMMEDIATE,
            ignoreFailedUpdates: false
        },
        function (downloadProgress) {
            console.log("Downloading " + downloadProgress.receivedBytes + " of " + downloadProgress.totalBytes + " bytes.");
        }
    );
}

**Comment by lostintangent** [comment]
@DefaultAlias Since you're calling sync in a button click instead of on app start, you need to call `codePush.notifyApplicationReady` on app start somewhere (within your `deviceready` handler?) in order to notify the CodePush runtime that the update was successful. It is likely that you're seeing the current behavior because the CodePush plugin is thinking the update failed, and therefore, is rolling it back.

You could test this theory by removing the `ignoreFailedUpdates` property when calling `sync`. If you don't keep getting the update notofication, it is because the plugin sees that it had failed in the past and is now ignoring it.

**Comment by DefaultAlias** [comment]
That was it. Thank you so much for clearing that up so quickly.

**Comment by lostintangent** [comment]
Your welcome! Thanks so much for giving CodePush a try. I'll make sure we add more detail to the docs to clarify this point for new users.
